services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=myLM
      - POSTGRES_USER=caper
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin4:
    image: elestio/pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
