###
GET http://localhost:3000/

###
GET http://localhost:3000/api/v1

###
GET http://localhost:3000/api/v1/user

###
POST  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "name": "Caper",
  "email": "caper@example.com",
  "password": "Strong123_456"
}

###
POST  http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "tol@mail.com",
  "password": "soytol123"
}
